### ISSUE TITLE
Failed registering node: connection refused

### ISSUE THREAD

**Issue by vicrac** [toshi-search/Toshi#114] opened 2019-01-22 20:24 UTC
After successfull build of release target (Ubuntu), while running  
```
$ RUST_BACKTRACE=1 ./target/release/toshi
```

I keep on getting:
```
 INFO  toshi > Settings { host: "127.0.0.1", port: 8080, path: "data/", place_addr: "0.0.0.0:8082", log_level: "info", writer_memory: 200000000, json_parsing_threads: 4, auto_commit_duration: 10, bulk_buffer_size: 10000, merge_policy: ConfigMergePolicy { kind: "log", min_merge_size: Some(8), min_layer_size: Some(10000), level_log_size: Some(0.75) }, consul_addr: "127.0.0.1:8500", cluster_name: "kitsune", enable_clustering: true, master: true, nodes: ["127.0.0.1:8081", "127.0.0.1:8082"] }

  ______         __   _   ____                 __
 /_  __/__  ___ / /  (_) / __/__ ___ _________/ /
  / / / _ \(_-</ _ \/ / _\ \/ -_) _ `/ __/ __/ _ \
 /_/  \___/___/_//_/_/ /___/\__/\_,_/_/  \__/_//_/
 Such Relevance, Much Index, Many Search, Wow
 
 ERROR toshi > Error: Failed registering Node: Inner(Inner(Error { kind: Connect, cause: Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } }))
thread 'main' panicked at 'internal error: entered unreachable code: Shutdown signal channel should not error, This is a bug.', src/bin/toshi.rs:68:22
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:227
             at src/libstd/panicking.rs:491
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   4: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   5: toshi::main::{{closure}}
   6: <futures::task_impl::Spawn<T>>::enter::{{closure}}
   7: toshi::main
   8: std::rt::lang_start::{{closure}}
   9: main
  10: __libc_start_main
  11: _start
```

netstat shows me that 8080 isn't in use by another process, and running command with sudo doesn't change anything. Message clearly state that this is a bug. So... is there a solution or not?

**Comment by hntd187** [comment] 2019-01-22 20:38
In your config change `enable_clustering` to false

**Comment by vicrac** [comment] 2019-01-22 21:21
It worked, thanks! However, I'm still curious how it actually works and I would enjoy a possibility to investigate to find the fix for the error, if you provide background or relevant sources. Thanks in advance.

**Comment by hntd187** [comment] 2019-01-22 21:42
The error is caused by the clustering attempting to register with consul as part of it's clustering initialization. Since you probably don't have consul running on localhost it error'ed. It appears to be behaving normal given the situation, but an issue that warrants the "bad error handling" label to denote a place where proper error handling would be able to give the use a less crappy error message.

**Comment by LucioFranco** [comment] 2019-01-24 20:44
yup, we should have a better error message there. To run consul though you can just use `consul agent -dev`.

**Comment by barrotsteindev** [comment] 2019-03-15 17:18
Shouldn't this issue be closed,
since #124 was merged into master?

**Closed** 2020-06-02 23:57 UTC
Labels: bad error handling
